version: '2'
services:
  cakephp:
    build: .
    depends_on:
      - mysql
    links:
      - "mysql"
    ports:
      - "8355:80"  
    volumes:
      - ./src:/var/www/html/
    environment:
      - SECURITY_SALT=SALT 
      - MYSQL_URL=mysql
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
    networks:
      - cakephp-docker-network
  mysql:
    image: mysql:5.6
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=cakephp
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - cakephp-docker-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wordpress-phpmyadmin-develop
    depends_on:
      - mysql
    restart: always
    ports:
      - "8354:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - cakephp-docker-network
volumes:
  db:

networks:
  cakephp-docker-network:
      driver: bridge
